<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // Criar permissões
        $permissions = [
            'sanctum.csrf-cookie' => 'Sanctum CSRF Cookie',
            'ignition.healthCheck' => 'Ignition Health Check',
            'ignition.executeSolution' => 'Ignition Execute Solution',
            'ignition.updateConfig' => 'Ignition Update Config',
            'api.user' => 'API User',
            'webhook.test' => 'Webhook Test',
            'webhook.handle' => 'Webhook Handle',
            'webhook.handleWhatsappMessage' => 'Webhook Handle Whatsapp Message',
            'bonus.store' => 'Bonus Store',
            'bonus.show' => 'Bonus Show',
            'bonus.update' => 'Bonus Update',
            'bonus.destroy' => 'Bonus Destroy',
            'achievement-types.index' => 'Achievement Types Index',
            'achievement-types.store' => 'Achievement Types Store',
            'achievement-types.show' => 'Achievement Types Show',
            'achievement-types.update' => 'Achievement Types Update',
            'achievement-types.destroy' => 'Achievement Types Destroy',
            'whatsapp.conversations' => 'Whatsapp Conversations',
            'whatsapp.messages' => 'Whatsapp Messages',
            'whatsapp.sendMessage' => 'Whatsapp Send Message',
            'whatsapp.markAsRead' => 'Whatsapp Mark As Read',
            'whatsapp.possibleMatches' => 'Whatsapp Possible Matches',
            'whatsapp.associate' => 'Whatsapp Associate',
            'whatsapp.unlink' => 'Whatsapp Unlink',
            'inscription.move' => 'Inscription Move',
            'feature-flags.toggle' => 'Feature Flags Toggle',
            'login' => 'Login',
            'login.login' => 'Login Login',
            'logout' => 'Logout',
            'password.request' => 'Password Request',
            'password.email' => 'Password Email',
            'password.reset' => 'Password Reset',
            'password.update' => 'Password Update',
            'password.confirm' => 'Password Confirm',
            'confirmpassword.confirm' => 'Confirm Password Confirm',
            'home' => 'Home',
            'clients.index' => 'Clients Index',
            'clients.create' => 'Clients Create',
            'clients.store' => 'Clients Store',
            'clients.show' => 'Clients Show',
            'clients.edit' => 'Clients Edit',
            'clients.update' => 'Clients Update',
            'clients.destroy' => 'Clients Destroy',
            'client-emails.store' => 'Client Emails Store',
            'client-emails.show' => 'Client Emails Show',
            'client-emails.update' => 'Client Emails Update',
            'client-emails.destroy' => 'Client Emails Destroy',
            'client-emails.set-primary' => 'Client Emails Set Primary',
            'client-emails.verify' => 'Client Emails Verify',
            'client-phones.store' => 'Client Phones Store',
            'client-phones.show' => 'Client Phones Show',
            'client-phones.update' => 'Client Phones Update',
            'client-phones.destroy' => 'Client Phones Destroy',
            'client-phones.set-primary' => 'Client Phones Set Primary',
            'client-companies.store' => 'Client Companies Store',
            'client-companies.show' => 'Client Companies Show',
            'client-companies.update' => 'Client Companies Update',
            'client-companies.destroy' => 'Client Companies Destroy',
            'client-companies.set-main' => 'Client Companies Set Main',
            'products.index' => 'Products Index',
            'products.create' => 'Products Create',
            'products.store' => 'Products Store',
            'products.show' => 'Products Show',
            'products.edit' => 'Products Edit',
            'products.update' => 'Products Update',
            'products.destroy' => 'Products Destroy',
            'inscriptions.index' => 'Inscriptions Index',
            'inscriptions.create' => 'Inscriptions Create',
            'inscriptions.store' => 'Inscriptions Store',
            'inscriptions.show' => 'Inscriptions Show',
            'inscriptions.edit' => 'Inscriptions Edit',
            'inscriptions.update' => 'Inscriptions Update',
            'inscriptions.destroy' => 'Inscriptions Destroy',
            'inscriptions.kanban-data' => 'Inscriptions Kanban Data',
            'import.index' => 'Import Index',
            'import.process' => 'Import Process',
            'import.template' => 'Import Template',
            'documents.index' => 'Documents Index',
            'documents.create' => 'Documents Create',
            'documents.upload' => 'Documents Upload',
            'documents.download' => 'Documents Download',
            'documents.destroy' => 'Documents Destroy',
            'preceptor-records.store' => 'Preceptor Records Store',
            'preceptor-records.destroy' => 'Preceptor Records Destroy',
            'payments.store' => 'Payments Store',
            'payments.destroy' => 'Payments Destroy',
            'sessions.store' => 'Sessions Store',
            'sessions.destroy' => 'Sessions Destroy',
            'diagnostics.store' => 'Diagnostics Store',
            'diagnostics.destroy' => 'Diagnostics Destroy',
            'achievements.store' => 'Achievements Store',
            'achievements.destroy' => 'Achievements Destroy',
            'follow-ups.store' => 'Follow Ups Store',
            'follow-ups.destroy' => 'Follow Ups Destroy',
            'documents.documents.store' => 'Documents Documents Store',
            'documents.documents.update' => 'Documents Documents Update',
            'documents.documents.destroy' => 'Documents Documents Destroy',
            'documents.documents.download' => 'Documents Documents Download',
            'documents.documents.toggle-verification' => 'Documents Documents Toggle Verification',
            'faturamentos.index' => 'Faturamentos Index',
            'faturamentos.store' => 'Faturamentos Store',
            'faturamentos.show' => 'Faturamentos Show',
            'faturamentos.update' => 'Faturamentos Update',
            'faturamentos.destroy' => 'Faturamentos Destroy',
            'renovacoes.index' => 'Renovacoes Index',
            'renovacoes.store' => 'Renovacoes Store',
            'renovacoes.show' => 'Renovacoes Show',
            'renovacoes.update' => 'Renovacoes Update',
            'renovacoes.destroy' => 'Renovacoes Destroy',
            'permissions.index' => 'Permissions Index',
            'permissions.create' => 'Permissions Create',
            'permissions.store' => 'Permissions Store',
            'permissions.show' => 'Permissions Show',
            'permissions.edit' => 'Permissions Edit',
            'permissions.update' => 'Permissions Update',
            'permissions.destroy' => 'Permissions Destroy',
            'roles.index' => 'Roles Index',
            'roles.create' => 'Roles Create',
            'roles.store' => 'Roles Store',
            'roles.show' => 'Roles Show',
            'roles.edit' => 'Roles Edit',
            'roles.update' => 'Roles Update',
            'roles.destroy' => 'Roles Destroy',
            'roles.toggle-status' => 'Roles Toggle Status',
            'users.index' => 'Users Index',
            'users.create' => 'Users Create',
            'users.store' => 'Users Store',
            'users.show' => 'Users Show',
            'users.edit' => 'Users Edit',
            'users.update' => 'Users Update',
            'users.destroy' => 'Users Destroy',
            'users.assign-role' => 'Users Assign Role',
            'users.remove-role' => 'Users Remove Role',
            'register' => 'Register',
            'register.register' => 'Register Register',
            'integrations.index' => 'Integrations Index',
            'integrations.zapsign' => 'Integrations Zapsign',
            'integrations.zapsign.settings' => 'Integrations Zapsign Settings',
            'integrations.zapsign.test' => 'Integrations Zapsign Test',
            'integrations.zapsign.templates' => 'Integrations Zapsign Templates',
            'integrations.zapsign.template-mappings' => 'Integrations Zapsign Template Mappings',
            'integrations.zapsign.template-mappings.create' => 'Integrations Zapsign Template Mappings Create',
            'integrations.zapsign.template-mappings.store' => 'Integrations Zapsign Template Mappings Store',
            'integrations.zapsign.template-mappings.edit' => 'Integrations Zapsign Template Mappings Edit',
            'integrations.zapsign.template-mappings.update' => 'Integrations Zapsign Template Mappings Update',
            'integrations.zapsign.template-mappings.destroy' => 'Integrations Zapsign Template Mappings Destroy',
            'integrations.zapsign.create-document' => 'Integrations Zapsign Create Document',
            'dashboard' => 'Dashboard',
            'achievement_types.index' => 'Achievement Types Index',
            'achievement_types.create' => 'Achievement Types Create',
            'achievement_types.store' => 'Achievement Types Store',
            'achievement_types.show' => 'Achievement Types Show',
            'achievement_types.edit' => 'Achievement Types Edit',
            'achievement_types.update' => 'Achievement Types Update',
            'achievement_types.destroy' => 'Achievement Types Destroy',
            'faixa-faturamentos.index' => 'Faixa Faturamentos Index',
            'faixa-faturamentos.create' => 'Faixa Faturamentos Create',
            'faixa-faturamentos.store' => 'Faixa Faturamentos Store',
            'faixa-faturamentos.show' => 'Faixa Faturamentos Show',
            'faixa-faturamentos.edit' => 'Faixa Faturamentos Edit',
            'faixa-faturamentos.update' => 'Faixa Faturamentos Update',
            'faixa-faturamentos.destroy' => 'Faixa Faturamentos Destroy',
            'faixa-faturamentos.api' => 'Faixa Faturamentos API',
            'integrations.zapsign.template-fields' => 'Integrations Zapsign Template Fields',
            'whatsapp.index' => 'Whatsapp Index',
            'whatsapp.config' => 'Whatsapp Config',
            'whatsapp.connect' => 'Whatsapp Connect',
            'whatsapp.disconnect' => 'Whatsapp Disconnect',
            'whatsapp.qr-code' => 'Whatsapp QR Code',
            'whatsapp.create-client' => 'Whatsapp Create Client',
            'webhook-logs.index' => 'Webhook Logs Index',
            'webhook-logs.show' => 'Webhook Logs Show',
            'webhook-logs.resend' => 'Webhook Logs Resend',
            'feature-flags.index' => 'Feature Flags Index',
            'feature-flags.create' => 'Feature Flags Create',
            'feature-flags.store' => 'Feature Flags Store',
            'feature-flags.show' => 'Feature Flags Show',
            'feature-flags.edit' => 'Feature Flags Edit',
            'feature-flags.update' => 'Feature Flags Update',
            'feature-flags.destroy' => 'Feature Flags Destroy',
        ];

        foreach ($permissions as $name => $description) {
            Permission::firstOrCreate(["name" => $name], ["guard_name" => "web"]);
        }

        // Criar cargos
        $roles = [
            'head-cs' => [
                'name' => 'Head de CS',
                'permissions' => array_keys($permissions), // Todas as permissões
            ],
            'especialista-suporte-ti' => [
                'name' => 'Especialista de Suporte (TI)',
                'permissions' => [
                    'users.index', 'users.create', 'users.store', 'users.show', 'users.edit', 'users.update', 'users.destroy',
                    'clients.index', 'clients.create', 'clients.store', 'clients.show', 'clients.edit', 'clients.update', 'clients.destroy',
                    'products.index', 'products.create', 'products.store', 'products.show', 'products.edit', 'products.update', 'products.destroy',
                    'inscriptions.index', 'inscriptions.create', 'inscriptions.store', 'inscriptions.show', 'inscriptions.edit', 'inscriptions.update', 'inscriptions.destroy',
                    'payments.store', 'payments.destroy',
                    'webhook-logs.index', 'webhook-logs.show', 'webhook-logs.resend',
                    'whatsapp.index', 'whatsapp.config', 'whatsapp.connect', 'whatsapp.disconnect', 'whatsapp.qr-code', 'whatsapp.create-client',
                    'feature-flags.index', 'feature-flags.create', 'feature-flags.store', 'feature-flags.show', 'feature-flags.edit', 'feature-flags.update', 'feature-flags.destroy', 'feature-flags.toggle',
                    'import.index', 'import.process', 'import.template',
                ],
            ],
            'coordenador-mentoria' => [
                'name' => 'Coordenador de Mentoria',
                'permissions' => [
                    'clients.index', 'clients.show', 'clients.edit', 'clients.update',
                    'inscriptions.index', 'inscriptions.show', 'inscriptions.edit', 'inscriptions.update', 'inscriptions.kanban-data',
                    'payments.store',
                    'achievements.store', 'achievements.destroy',
                    'bonus.store', 'bonus.show', 'bonus.update', 'bonus.destroy',
                    'whatsapp.conversations', 'whatsapp.messages', 'whatsapp.sendMessage', 'whatsapp.markAsRead', 'whatsapp.possibleMatches', 'whatsapp.associate', 'whatsapp.unlink',
                    'faturamentos.index', 'faturamentos.show',
                    'renovacoes.index', 'renovacoes.show',
                ],
            ],
            'especialista-customer-success' => [
                'name' => 'Especialista em Customer Success',
                'permissions' => [
                    'clients.index', 'clients.show', 'clients.edit', 'clients.update',
                    'inscriptions.index', 'inscriptions.show', 'inscriptions.edit', 'inscriptions.update', 'inscriptions.kanban-data',
                    'payments.store',
                    'faturamentos.index', 'faturamentos.store', 'faturamentos.show', 'faturamentos.update', 'faturamentos.destroy',
                    'renovacoes.index', 'renovacoes.store', 'renovacoes.show', 'renovacoes.update', 'renovacoes.destroy',
                    'whatsapp.conversations', 'whatsapp.messages', 'whatsapp.sendMessage', 'whatsapp.markAsRead', 'whatsapp.possibleMatches', 'whatsapp.associate', 'whatsapp.unlink',
                ],
            ],
            'especialista-suporte-cliente' => [
                'name' => 'Especialista em Suporte ao Cliente',
                'permissions' => [
                    'clients.index', 'clients.show',
                    'inscriptions.index', 'inscriptions.show',
                    'payments.store',
                    'whatsapp.conversations', 'whatsapp.messages', 'whatsapp.sendMessage', 'whatsapp.markAsRead', 'whatsapp.possibleMatches', 'whatsapp.associate', 'whatsapp.unlink',
                ],
            ],
        ];

        foreach ($roles as $slug => $roleData) {
            $role = Role::firstOrCreate(["name" => $slug], ["guard_name" => "web"]);
            $role->syncPermissions($roleData["permissions"]);
        }
    }
}


