version: '3.8'

services:
  application:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    image: md1-sistema
    container_name: md1-sistema
    tty: true
    ports: 
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel_app
    command: >
      sh -c "
      chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
      chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
      php artisan storage:link &&
      php-fpm
      "

  nginx:
    image: nginx:alpine
    container_name: md1-sistema_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_app
      # - md1-sistema_shared_network

  mysql:
    image: mysql:latest
    container_name: md1-sistema_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: md1-sistema_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: dev123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_app
      # - md1-sistema_shared_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: md1-sistema_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql                       # Nome do serviço MySQL
      PMA_USER: root                   # Nome de usuário do MySQL
      PMA_PASSWORD: root123            # Senha do usuário do MySQL
      
      UPLOAD_LIMIT: 10M
      PMA_UPLOAD_MAX_FILESIZE: 10M
      PMA_MAX_UPLOAD_SIZE: 10M
      PHP_UPLOAD_MAX_FILESIZE: 10M
      PHP_POST_MAX_SIZE: 10M
    ports:
      - "8080:80"                           # Exponha a porta 8080
    networks:
      - laravel_app

volumes:
  mysql_data:                              # Volume para persistência do MySQL

networks:
  laravel_app:
    driver: bridge
  # md1-sistema_shared_network:
  #   external: true
